server:
  port: 8000

spring:
  application:
    name: feign-consumer

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.107:8888/eureka/,http://192.168.0.107:8889/eureka/