server:
  port: 5000

spring:
  application:
    name: api-gateway

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.105:8888/eureka/,http://192.168.0.105:8889/eureka/

zuul:
  routes:
    hello-service:
      path: /hello-service/**
      serviceId: hello-service

#zuul.TokenFilter.pre.disable=true